### ISSUE TITLE
Missing environment variable API_KEY

### ISSUE THREAD

**Issue by molant** [strichpunkt-design/10k-solograph#1]
Your site is deployed in http://solograph-10kapart2016.azurewebsites.net/ but it doesn't have the API_KEY environment variable so it doesn't work.

/cc @aarongustafson

**Comment by thomasmichelbach** [comment]
hi @molant thanks for the quick reply! We've passed the API_KEY with our submission (i guess you've asked for env vars / app settings via the submission form). How can we access those variables? Aren't they part of the $_ENV vars in an azure environment? Any other valuable trick how we can pass this kind of data in the current environment?

Thanks and all the best!

**Comment by molant** [comment]
Looks like there was a problem with the deployment. Site is now working!

Thanks!

**Comment by thomasmichelbach** [comment]
Seems to reoccur after a fresh deployment, could you please have a look @molant  :/

**Comment by molant** [comment]
API Key was in the env. In Azure you have to use `getenv` to get the value. I've changed it but keep it in mind for the future :)
